name: Update readme

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate readme
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        shell: pwsh
        run: . ./build-svg.ps1
# COMMIT FILE USES
      - name: Commit changes
        uses: EndBug/add-and-commit@v4 
        with:
          author_name: Grant Steinfeld
          author_email: grant.steinfeld.tech@gmail.com
          message: "Auto updating my readme"
          add: "*.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.BABU }}
