name: Update dash BME

on:
  push

jobs:
  dash:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate Dashboard BME
        shell: pwsh
        run: . ./build-dash-BME.ps1
# COMMIT FILE USES
      - name: Commit changes
        uses: EndBug/add-and-commit@v4 
        with:
          author_name: Grant Steinfeld
          author_email: grant.steinfeld.tech@gmail.com
          message: "Auto updating my dash"
          add: "*.md"
        env:
          GITHUB_TOKEN: ${{ secrets.BABU }}
